### ISSUE TITLE
read csv instead of rds file

### ISSUE THREAD

**Issue by waltertakens** [rivm-syso/Samen-analyseren-tool#4]
The tool was installed on ubuntu-20-04-focal-fossa-linux and works fine.

Currently the global.r reads an rds example file.
I would like to read a csv file instead, to be able to display  data of the Gouda community instead.
In R my programming skills are limited, as a first attempt I converted the example rds file to a csv:

file <- "HLL_voorbeeld_data.RDS"
input_df <- readRDS(file)
write.csv(input_df,"HLLexport.csv")
dat <- read.csv("HLLexport.csv")
saveRDS(dat,"HLLimportexport.RDS")

Then adapted the global.R
#original
#input_df <- readRDS(file)

#Attempt1
input_df <-read.csv("HLLexport.csv", header=TRUE, sep=",")

#Attempt2
input_df <- readRDS("HLLimportexport.RDS")

Both Attempt1 as Attempt2 result in an:
"ERROR: ‘min’ not meaningful for factors" and no working application.

Any suggestions ?
Thanks

**Comment by ruiterdh** [comment]
There are a few issues with your write.csv and read.csv.
See below for example code. You should set row.names to FALSE in write.csv otherwise you will get an extra column in your csv file.
And specify the class of the columns when reading (I use read.table here)

file <- "HLL_voorbeeld_data.RDS"
input_df <- readRDS(file)
write.csv(input_df,"HLLexport.csv", row.names = FALSE)
dat <- read.table("HLLexport.csv", sep = ",", header=TRUE,
                colClasses = c("character", "character", rep("numeric",12), "character", "character"))
dat$date = as.POSIXct(dat$date)
saveRDS(dat,"HLLimportexport.RDS")

And in Global.R
input_df  <- readRDS("HLLimportexport.RDS")

**Comment by waltertakens** [comment]
Thanks, works like a charm !
